/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author xochi
 */
public class Ventana2 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana2
     */
    public Ventana2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nombreImagen = new javax.swing.JLabel();
        formatoImagen = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        alto = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ancho = new javax.swing.JLabel();
        filtroGris = new javax.swing.JButton();
        imagenOriginal = new javax.swing.JButton();
        noventa = new javax.swing.JButton();
        cientoO = new javax.swing.JButton();
        dosC = new javax.swing.JButton();
        datosImg2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nom_2 = new javax.swing.JLabel();
        fort_2 = new javax.swing.JLabel();
        alt_2 = new javax.swing.JLabel();
        anch_2 = new javax.swing.JLabel();
        Panel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        valor_00 = new javax.swing.JTextField();
        valor_01 = new javax.swing.JTextField();
        valor_02 = new javax.swing.JTextField();
        valor_10 = new javax.swing.JTextField();
        valor_11 = new javax.swing.JTextField();
        valor_12 = new javax.swing.JTextField();
        valor_20 = new javax.swing.JTextField();
        valor_21 = new javax.swing.JTextField();
        valor_22 = new javax.swing.JTextField();
        enviarKernel = new javax.swing.JButton();
        histograma = new javax.swing.JButton();
        contenedorImagen = new javax.swing.JLabel();
        aplicaFiltro = new javax.swing.JButton();
        filtros = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        zoom = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        abreImagen = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        opA = new javax.swing.JMenuItem();
        opO = new javax.swing.JMenuItem();
        opX = new javax.swing.JMenuItem();
        opN = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mediaArit = new javax.swing.JMenuItem();
        mediaGeo = new javax.swing.JMenuItem();
        mediana = new javax.swing.JMenuItem();
        max = new javax.swing.JMenuItem();
        min = new javax.swing.JMenuItem();
        puntoMedio = new javax.swing.JMenuItem();
        mediaSeccion = new javax.swing.JMenuItem();
        mediaAdaptive = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        ILPF = new javax.swing.JMenuItem();
        BLPF = new javax.swing.JMenuItem();
        IHPF = new javax.swing.JMenuItem();
        BHPF = new javax.swing.JMenuItem();
        IBPF = new javax.swing.JMenuItem();
        IBSF = new javax.swing.JMenuItem();
        BBPF = new javax.swing.JMenuItem();
        BBSF = new javax.swing.JMenuItem();
        gaussian = new javax.swing.JMenuItem();
        espectro = new javax.swing.JMenuItem();
        RGBtoHSI = new javax.swing.JMenu();
        HSI = new javax.swing.JMenuItem();
        cmy = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        erosion = new javax.swing.JMenuItem();
        dilatacion = new javax.swing.JMenuItem();
        apertura = new javax.swing.JMenuItem();
        cierre = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(37, 71, 95));

        jLabel3.setBackground(new java.awt.Color(37, 71, 95));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(208, 215, 215));
        jLabel3.setText("Nombre de la Imagen :");

        jLabel4.setBackground(new java.awt.Color(37, 71, 95));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(208, 215, 215));
        jLabel4.setText("Formato: ");

        nombreImagen.setBackground(new java.awt.Color(37, 71, 95));
        nombreImagen.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        nombreImagen.setForeground(new java.awt.Color(208, 215, 215));

        formatoImagen.setBackground(new java.awt.Color(37, 71, 95));
        formatoImagen.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        formatoImagen.setForeground(new java.awt.Color(208, 215, 215));

        jLabel7.setBackground(new java.awt.Color(37, 71, 95));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(208, 215, 215));
        jLabel7.setText("Altura:");

        alto.setBackground(new java.awt.Color(37, 71, 95));
        alto.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        alto.setForeground(new java.awt.Color(208, 215, 215));

        jLabel9.setBackground(new java.awt.Color(37, 71, 95));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(208, 215, 215));
        jLabel9.setText("Ancho:");

        ancho.setBackground(new java.awt.Color(37, 71, 95));
        ancho.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        ancho.setForeground(new java.awt.Color(208, 215, 215));

        filtroGris.setBackground(new java.awt.Color(208, 215, 215));
        filtroGris.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        filtroGris.setForeground(new java.awt.Color(0, 0, 0));
        filtroGris.setText("Aplicar Filtro Gris");

        imagenOriginal.setBackground(new java.awt.Color(208, 215, 215));
        imagenOriginal.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        imagenOriginal.setForeground(new java.awt.Color(0, 0, 0));
        imagenOriginal.setText("Regresar Imagen Original");

        noventa.setBackground(new java.awt.Color(208, 215, 215));
        noventa.setIcon(new javax.swing.ImageIcon("C:\\Users\\xochi\\OneDrive\\Escritorio\\Iconos\\90 (1).png")); // NOI18N

        cientoO.setBackground(new java.awt.Color(208, 215, 215));
        cientoO.setIcon(new javax.swing.ImageIcon("C:\\Users\\xochi\\OneDrive\\Escritorio\\Iconos\\180 (1).png")); // NOI18N

        dosC.setBackground(new java.awt.Color(208, 215, 215));
        dosC.setForeground(new java.awt.Color(208, 215, 215));
        dosC.setIcon(new javax.swing.ImageIcon("C:\\Users\\xochi\\OneDrive\\Escritorio\\Iconos\\270 (1).png")); // NOI18N

        datosImg2.setBackground(new java.awt.Color(37, 71, 95));

        jLabel1.setBackground(new java.awt.Color(37, 71, 95));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(208, 215, 215));
        jLabel1.setText("Datos de la Segunda Imagen");

        jLabel5.setBackground(new java.awt.Color(37, 71, 95));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(208, 215, 215));
        jLabel5.setText("Nombre: ");

        jLabel6.setBackground(new java.awt.Color(37, 71, 95));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(208, 215, 215));
        jLabel6.setText("Formato:");

        jLabel8.setBackground(new java.awt.Color(37, 71, 95));
        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(208, 215, 215));
        jLabel8.setText("Altura: ");

        jLabel10.setBackground(new java.awt.Color(37, 71, 95));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(208, 215, 215));
        jLabel10.setText("Ancho: ");

        nom_2.setBackground(new java.awt.Color(37, 71, 95));
        nom_2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nom_2.setForeground(new java.awt.Color(208, 215, 215));
        nom_2.setText("jLabel11");

        fort_2.setBackground(new java.awt.Color(37, 71, 95));
        fort_2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fort_2.setForeground(new java.awt.Color(208, 215, 215));
        fort_2.setText("jLabel12");

        alt_2.setBackground(new java.awt.Color(37, 71, 95));
        alt_2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        alt_2.setForeground(new java.awt.Color(208, 215, 215));
        alt_2.setText("jLabel13");

        anch_2.setBackground(new java.awt.Color(37, 71, 95));
        anch_2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        anch_2.setForeground(new java.awt.Color(208, 215, 215));
        anch_2.setText("jLabel14");

        javax.swing.GroupLayout datosImg2Layout = new javax.swing.GroupLayout(datosImg2);
        datosImg2.setLayout(datosImg2Layout);
        datosImg2Layout.setHorizontalGroup(
            datosImg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosImg2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(datosImg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addGap(27, 27, 27)
                .addGroup(datosImg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(anch_2)
                    .addComponent(alt_2)
                    .addComponent(fort_2)
                    .addComponent(jLabel1)
                    .addComponent(nom_2))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        datosImg2Layout.setVerticalGroup(
            datosImg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosImg2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(datosImg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nom_2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(datosImg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(fort_2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(datosImg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(alt_2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(datosImg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(anch_2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panel3.setBackground(new java.awt.Color(37, 71, 95));

        jLabel11.setBackground(new java.awt.Color(37, 71, 95));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(208, 215, 215));
        jLabel11.setText("Parametros Kernel");

        enviarKernel.setBackground(new java.awt.Color(208, 215, 215));
        enviarKernel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        enviarKernel.setForeground(new java.awt.Color(0, 0, 0));
        enviarKernel.setText("Enviar");

        javax.swing.GroupLayout Panel3Layout = new javax.swing.GroupLayout(Panel3);
        Panel3.setLayout(Panel3Layout);
        Panel3Layout.setHorizontalGroup(
            Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(enviarKernel)
                .addGap(64, 64, 64))
            .addGroup(Panel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addGroup(Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(Panel3Layout.createSequentialGroup()
                            .addComponent(valor_20, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(valor_21, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(valor_22, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Panel3Layout.createSequentialGroup()
                            .addComponent(valor_00, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(valor_01, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(valor_02, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Panel3Layout.createSequentialGroup()
                            .addComponent(valor_10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(valor_11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(valor_12, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        Panel3Layout.setVerticalGroup(
            Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valor_00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valor_01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valor_02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valor_10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valor_11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valor_12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valor_20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valor_21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valor_22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enviarKernel)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        histograma.setBackground(new java.awt.Color(208, 215, 215));
        histograma.setForeground(new java.awt.Color(208, 215, 215));
        histograma.setIcon(new javax.swing.ImageIcon("C:\\Users\\xochi\\OneDrive\\Escritorio\\Iconos\\iloveimg-resized\\histograma.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(nombreImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(ancho, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(imagenOriginal)
                    .addComponent(filtroGris)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(18, 18, 18)
                            .addComponent(alto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(formatoImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(noventa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cientoO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dosC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(histograma, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(datosImg2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nombreImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(formatoImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(alto, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(ancho, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(filtroGris)
                        .addGap(18, 18, 18)
                        .addComponent(imagenOriginal)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(noventa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cientoO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(histograma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(dosC))
                .addGap(33, 33, 33)
                .addComponent(datosImg2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        contenedorImagen.setText("jLabel1");

        aplicaFiltro.setBackground(new java.awt.Color(208, 215, 215));
        aplicaFiltro.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        aplicaFiltro.setForeground(new java.awt.Color(0, 0, 0));
        aplicaFiltro.setText("Aplicar Filtro");

        filtros.setBackground(new java.awt.Color(208, 215, 215));
        filtros.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        filtros.setForeground(new java.awt.Color(0, 0, 0));
        filtros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inverso o Negativo", "Umbral", "Umbral Inverso", "Umbral Binario", "Umbral Binario Inverso", "Umbral en Gris", "Umbral en Gris Inverso", "Extension", "Reduccion de Niveles de Gris", "Suma", "Resta", "Convolucion", " " }));
        filtros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrosActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Seleccione el filtro que desee aplicar");

        zoom.setBackground(new java.awt.Color(208, 215, 215));
        zoom.setIcon(new javax.swing.ImageIcon("C:\\Users\\xochi\\OneDrive\\Escritorio\\Iconos\\iloveimg-resized\\zoom.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(aplicaFiltro)
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(filtros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(zoom))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(contenedorImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(contenedorImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(filtros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addComponent(aplicaFiltro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(zoom, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(52, 52, 52))
        );

        jMenu1.setText("Acciones");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        abreImagen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        abreImagen.setText("Abrir Imagen");
        jMenu1.add(abreImagen);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Operaciones Logicas");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        opA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        opA.setText("AND");
        jMenu2.add(opA);

        opO.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        opO.setText("OR");
        jMenu2.add(opO);

        opX.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        opX.setText("XORT");
        jMenu2.add(opX);

        opN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        opN.setText("NOT");
        jMenu2.add(opN);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Filtros Restauracion");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        mediaArit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mediaArit.setText("Media Aritmetica");
        jMenu5.add(mediaArit);

        mediaGeo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mediaGeo.setText("Media Geometrica");
        jMenu5.add(mediaGeo);

        mediana.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mediana.setText("Mediana");
        jMenu5.add(mediana);

        max.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        max.setText("Max");
        max.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxActionPerformed(evt);
            }
        });
        jMenu5.add(max);

        min.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        min.setText("Min");
        jMenu5.add(min);

        puntoMedio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        puntoMedio.setText("Punto Medio");
        jMenu5.add(puntoMedio);

        mediaSeccion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mediaSeccion.setText("Media Seccion");
        jMenu5.add(mediaSeccion);

        mediaAdaptive.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mediaAdaptive.setText("Media Adaptativo");
        jMenu5.add(mediaAdaptive);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Filtros Frecuencia");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        ILPF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ILPF.setText("Ideal Low Pass Filter");
        jMenu6.add(ILPF);

        BLPF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BLPF.setText("Butterworth Low Pass Filter");
        jMenu6.add(BLPF);

        IHPF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IHPF.setText("Ideal High Pass Filter");
        jMenu6.add(IHPF);

        BHPF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BHPF.setText("Butterworth High Pass Filter");
        jMenu6.add(BHPF);

        IBPF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IBPF.setText("Ideal Band Pass Filter");
        jMenu6.add(IBPF);

        IBSF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IBSF.setText("Ideal Band Stop Filter");
        jMenu6.add(IBSF);

        BBPF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BBPF.setText("Butterworth Band Pass Filter");
        jMenu6.add(BBPF);

        BBSF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BBSF.setText("Butterworth Band Stop Filter");
        jMenu6.add(BBSF);

        gaussian.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        gaussian.setText("Punto Extra");
        jMenu6.add(gaussian);

        espectro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        espectro.setText("Espectro");
        jMenu6.add(espectro);

        jMenuBar1.add(jMenu6);

        RGBtoHSI.setText("Conversion de Modelos");
        RGBtoHSI.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        HSI.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        HSI.setText("RGB a HSI");
        RGBtoHSI.add(HSI);

        cmy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmy.setText("RGB a CMY");
        RGBtoHSI.add(cmy);

        jMenuBar1.add(RGBtoHSI);

        jMenu8.setText("Morfologia");
        jMenu8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        erosion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        erosion.setText("Erosion");
        jMenu8.add(erosion);

        dilatacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dilatacion.setText("Dilatacion");
        jMenu8.add(dilatacion);

        apertura.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        apertura.setText("Apertura");
        jMenu8.add(apertura);

        cierre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cierre.setText("Cierre");
        jMenu8.add(cierre);

        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void filtrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filtrosActionPerformed

    private void maxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem BBPF;
    public javax.swing.JMenuItem BBSF;
    public javax.swing.JMenuItem BHPF;
    public javax.swing.JMenuItem BLPF;
    public javax.swing.JMenuItem HSI;
    public javax.swing.JMenuItem IBPF;
    public javax.swing.JMenuItem IBSF;
    public javax.swing.JMenuItem IHPF;
    public javax.swing.JMenuItem ILPF;
    public javax.swing.JPanel Panel3;
    private javax.swing.JMenu RGBtoHSI;
    public javax.swing.JMenuItem abreImagen;
    public javax.swing.JLabel alt_2;
    public javax.swing.JLabel alto;
    public javax.swing.JLabel anch_2;
    public javax.swing.JLabel ancho;
    public javax.swing.JMenuItem apertura;
    public javax.swing.JButton aplicaFiltro;
    public javax.swing.JButton cientoO;
    public javax.swing.JMenuItem cierre;
    public javax.swing.JMenuItem cmy;
    public javax.swing.JLabel contenedorImagen;
    public javax.swing.JPanel datosImg2;
    public javax.swing.JMenuItem dilatacion;
    public javax.swing.JButton dosC;
    public javax.swing.JButton enviarKernel;
    public javax.swing.JMenuItem erosion;
    public javax.swing.JMenuItem espectro;
    public javax.swing.JButton filtroGris;
    public javax.swing.JComboBox<String> filtros;
    public javax.swing.JLabel formatoImagen;
    public javax.swing.JLabel fort_2;
    public javax.swing.JMenuItem gaussian;
    public javax.swing.JButton histograma;
    public javax.swing.JButton imagenOriginal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JMenuItem max;
    public javax.swing.JMenuItem mediaAdaptive;
    public javax.swing.JMenuItem mediaArit;
    public javax.swing.JMenuItem mediaGeo;
    public javax.swing.JMenuItem mediaSeccion;
    public javax.swing.JMenuItem mediana;
    public javax.swing.JMenuItem min;
    public javax.swing.JLabel nom_2;
    public javax.swing.JLabel nombreImagen;
    public javax.swing.JButton noventa;
    public javax.swing.JMenuItem opA;
    public javax.swing.JMenuItem opN;
    public javax.swing.JMenuItem opO;
    public javax.swing.JMenuItem opX;
    public javax.swing.JMenuItem puntoMedio;
    public javax.swing.JTextField valor_00;
    public javax.swing.JTextField valor_01;
    public javax.swing.JTextField valor_02;
    public javax.swing.JTextField valor_10;
    public javax.swing.JTextField valor_11;
    public javax.swing.JTextField valor_12;
    public javax.swing.JTextField valor_20;
    public javax.swing.JTextField valor_21;
    public javax.swing.JTextField valor_22;
    public javax.swing.JButton zoom;
    // End of variables declaration//GEN-END:variables
}
